// "About muSQL" (#119): the version, and the licences of everything that is shipped.
//
// The list is ui/credits.json, generated by `just credits` (src-tauri/src/credits.rs)
// and committed. It is fetched when the dialog is first opened, not at startup: it is
// close to a megabyte, almost all of it licence text.
//
// Everything is built with DOM calls; nothing from the file is parsed as HTML.
// Entry point: window.openAbout() (Help menu -> "About muSQL").
(function () {
  const REPO_URL = "https://github.com/kan/musql";

  let overlay = null;
  let listEl = null;
  let countEl = null;
  let filterEl = null;
  let credits = null; // { packages, texts } once loaded

  function tr(key, fallback, params) {
    return typeof window.t === "function" ? window.t(key, params) : fallback;
  }

  function invokeTauri(cmd, args) {
    if (window.__TAURI__ && window.__TAURI__.core) {
      return window.__TAURI__.core.invoke(cmd, args);
    }
    return Promise.reject(new Error("Tauri API unavailable"));
  }

  function el(tag, className, text) {
    const node = document.createElement(tag);
    if (className) node.className = className;
    if (text !== undefined) node.textContent = text;
    return node;
  }

  function externalLink(label, url) {
    const a = el("a", "about-link", label);
    a.href = url;
    a.addEventListener("click", (e) => {
      e.preventDefault();
      invokeTauri("open_external", { url }).catch(() => {});
    });
    return a;
  }

  // One package: a summary line, and its licence text(s) once it is opened.
  function packageRow(pkg) {
    const details = el("details", "about-pkg");
    const summary = el("summary", "about-pkg-summary");
    summary.appendChild(el("span", "about-pkg-name", pkg.name));
    if (pkg.version) summary.appendChild(el("span", "about-pkg-version", pkg.version));
    summary.appendChild(el("span", "about-pkg-license", pkg.license));
    details.appendChild(summary);

    // Built on first open: 430 packages times a licence text is a lot of DOM to make
    // for a dialog most people open to read the version.
    details.addEventListener("toggle", () => {
      if (!details.open || details.dataset.built) return;
      details.dataset.built = "1";
      const body = el("div", "about-pkg-body");
      // open_external only accepts https. The generator asserts that every URL is.
      if (pkg.url.startsWith("https://")) body.appendChild(externalLink(pkg.url, pkg.url));
      if (pkg.standard) {
        // The package ships no licence text; what follows includes the standard text of
        // its licence, whose copyright line is a placeholder. Say whose it is.
        const authors = (pkg.authors || []).join(", ") ||
          tr("about_contributors", "the {name} contributors", { name: pkg.name });
        body.appendChild(el("p", "about-pkg-note",
          tr("about_standard_text", "Standard licence text; the package does not ship its own.") +
          " " + tr("about_authors", "Authors: {authors}", { authors })));
      }
      for (const index of pkg.texts) {
        body.appendChild(el("pre", "about-license-text", credits.texts[index]));
      }
      details.appendChild(body);
    });
    return details;
  }

  function renderList() {
    const query = filterEl.value.trim().toLowerCase();
    const shown = credits.packages.filter((pkg) =>
      !query || pkg.name.toLowerCase().includes(query) || pkg.license.toLowerCase().includes(query));
    listEl.textContent = "";
    const frag = document.createDocumentFragment();
    for (const pkg of shown) frag.appendChild(packageRow(pkg));
    listEl.appendChild(frag);
    countEl.textContent = tr("about_count", "{shown} of {total}", {
      shown: shown.length,
      total: credits.packages.length,
    });
  }

  async function loadCredits() {
    if (credits) return;
    listEl.textContent = tr("manual_loading", "Loading...");
    try {
      // no-store: the file changes with every release, under the same URL.
      const res = await fetch("./credits.json", { cache: "no-store" });
      if (!res.ok) throw new Error("HTTP " + res.status);
      credits = await res.json();
    } catch (e) {
      listEl.textContent = tr("about_load_error", "Could not load the licence list.");
      console.warn("credits.json failed to load:", e);
      return;
    }
    renderList();
  }

  function close() {
    if (overlay) overlay.classList.add("hidden");
  }

  function ensureOverlay() {
    if (overlay) return;
    overlay = el("div", "modal-overlay manual-overlay about-overlay hidden");
    const box = el("div", "manual-box");

    const header = el("div", "manual-header");
    const title = el("strong", "about-title", "muSQL");
    header.appendChild(title);
    const versionEl = el("span", "about-version");
    header.appendChild(versionEl);
    const spacer = el("div");
    spacer.style.flex = "1";
    header.appendChild(spacer);
    header.appendChild(externalLink("GitHub", REPO_URL));
    const closeBtn = el("button", "ghost manual-nav-btn manual-close-btn", "✕");
    closeBtn.type = "button";
    closeBtn.addEventListener("click", close);
    header.appendChild(closeBtn);
    box.appendChild(header);

    const content = el("div", "about-content");
    const heading = el("h3", "about-heading");
    heading.dataset.i18n = "about_licenses";
    heading.textContent = tr("about_licenses", "Open source licences");
    content.appendChild(heading);
    const note = el("p", "about-note");
    note.dataset.i18n = "about_licenses_note";
    note.textContent = tr("about_licenses_note",
      "muSQL is built with the following open source software. Select an entry to read its licence.");
    content.appendChild(note);

    const tools = el("div", "about-tools");
    filterEl = el("input", "about-filter");
    filterEl.type = "search";
    filterEl.autocomplete = "off";
    filterEl.dataset.i18nPlaceholder = "about_filter";
    filterEl.placeholder = tr("about_filter", "Filter by name or licence");
    filterEl.addEventListener("input", () => { if (credits) renderList(); });
    tools.appendChild(filterEl);
    countEl = el("span", "about-count");
    tools.appendChild(countEl);
    content.appendChild(tools);

    listEl = el("div", "about-list");
    content.appendChild(listEl);
    box.appendChild(content);

    overlay.appendChild(box);
    overlay.addEventListener("mousedown", (e) => {
      if (e.target === overlay) close();
    });
    document.body.appendChild(overlay);

    const app = window.__TAURI__ && window.__TAURI__.app;
    if (app) {
      app.getVersion().then((v) => { versionEl.textContent = "v" + v; }).catch(() => {});
    }
  }

  function openAbout() {
    ensureOverlay();
    overlay.classList.remove("hidden");
    // Re-render when already loaded: the count and the notes are built strings, and the
    // language may have changed since.
    if (credits) renderList();
    else loadCredits();
  }

  document.addEventListener("keydown", (e) => {
    if (e.key !== "Escape" || !overlay || overlay.classList.contains("hidden")) return;
    // The manual (F1) opens on top of this dialog; Escape then closes only the manual.
    if (document.querySelector(".manual-overlay:not(.about-overlay):not(.hidden)")) return;
    e.stopPropagation();
    close();
  });

  window.openAbout = openAbout;
})();
